Merge the entire project
srueda27/NYT-Clone pull request #3
Opened 2019-12-09 22:55 UTC by srueda27

Finishing up the project, a basic HTML/CSS clone of the [New York Times](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html) website

2019-12-09 23:30 UTC, pelzolga123 commented on index.html
> +                    <a href="#">Today's papers</a> -->
Commented code should be deleted.

2019-12-09 23:31 UTC, pelzolga123 requested changes
Project needs some styling corrections, sticky footer is missing, leftmost bottom part should contain links.

2019-12-09 23:31 UTC, pelzolga123 commented
## Hi Team, your project looks :+1: great!
### But still it needs some changes: 
* [ ] Design is a little messed up in this parts, it should be fixed:
![image](https://user-images.githubusercontent.com/20416431/70481378-13cc1500-1aeb-11ea-808d-17b2cce46f81.png)

![image](https://user-images.githubusercontent.com/20416431/70481469-5988dd80-1aeb-11ea-80c3-a6eed9517a55.png)

* [ ] Bottom part should be aligned like on original website:
![image](https://user-images.githubusercontent.com/20416431/70481594-c00dfb80-1aeb-11ea-94a8-9e975da818e2.png)


Original:
![image](https://user-images.githubusercontent.com/20416431/70352486-e88bc080-1873-11ea-96a3-b1a3e82aff5a.png)

* [ ] Bottom part should contain links to other articles with image previews on the leftmost side.

* [ ] Footer should have a fixed position (it sticks to the bottom part of the screen):
![image](https://user-images.githubusercontent.com/20416431/70352647-43bdb300-1874-11ea-9d67-65dca68d961d.png)

### Please kindly fix the above issues and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

2019-12-10 20:40 UTC, shshamim63 commented
## Status :green_apple: !! Approved !! :green_apple: 
___
Hi @srueda27 & @codecell :wave,
Well done :clap: . You have done a great job. I can see all the items are rendering as they should. Code looks neat and clean. You have used float on most of the items and used position too. In a word tremendous. 
___
#### This :+1:  is from me. you can merge it and don't forget to fill the project completion form.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain
[Linkedin](https://www.linkedin.com/in/shakhawathossainshamim/) | [Slack](@Shakhawat)

2019-12-10 21:27 UTC, merged